# Use the official ROS2 Galactic desktop image as the base image
FROM osrf/ros:galactic-desktop

RUN apt-get update && \
    apt-get install -y \
        gazebo11 \
        ros-galactic-gazebo-ros-pkgs \
        ros-galactic-ros2-controllers \
        ros-galactic-joint-state-publisher \
        ros-galactic-robot-state-publisher \
        ros-galactic-robot-localization \
        ros-galactic-xacro \
        ros-galactic-tf2-ros \
        ros-galactic-tf2-tools \
        ros-galactic-robot-state-publisher \
        ros-galactic-ament-cmake \
    && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /ros2_ws

# Copy your ROS2 package(s) into the workspace
COPY ./src/ /ros2_ws/src/

# Build the workspace
RUN /bin/bash -c "source /opt/ros/galactic/setup.bash && colcon build "


# Specify a command that runs indefinitely

CMD /bin/bash -c "source /ros2_ws/install/setup.sh && ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=True"
