# Base image
FROM osrf/ros:galactic-desktop

# Install required packages
RUN apt-get update && apt-get install -y \
    ros-galactic-joy \
    ros-galactic-teleop-twist-joy \
    ros-galactic-teleop-twist-keyboard \
    ros-galactic-rviz2 \
    ros-galactic-dynamixel-sdk \
    ros-galactic-turtlebot3-msgs \
    ros-galactic-turtlebot3

# Set up the colcon workspace
RUN mkdir -p /ros2_ws/src
WORKDIR /ros2_ws

# Copy the map, configuration, and launch files needed for navigation
COPY ./src /ros2_ws/src

# Build the workspace
RUN /bin/bash -c "source /opt/ros/galactic/setup.bash && colcon build"

# Source the setup.bash file automatically when the container starts
RUN echo "source /ros2_ws/install/setup.bash" >> ~/.bashrc

# Command to run when starting the container
CMD /bin/bash -c "sleep 30 && source /opt/ros/galactic/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch tortoisebot_slam cartographer.launch.py use_sim_time:=True"
