# Base image
FROM osrf/ros:noetic-desktop-full-focal

# Install required ROS packages
# Adding ROS packages required by your project for direct installation
RUN apt-get update && apt-get install -y \
    ros-noetic-genmsg \
    ros-noetic-geometry-msgs \
    ros-noetic-nav-msgs \
    ros-noetic-std-msgs \
    ros-noetic-actionlib-msgs \
    ros-noetic-actionlib 


# Set up the catkin workspace
RUN mkdir -p /catkin_ws/src
WORKDIR /catkin_ws


# Copy your ROS package source
COPY ./src /catkin_ws/src


# Build the workspace
RUN /bin/bash -c ". /opt/ros/noetic/setup.bash && catkin_make"


# Source the setup.bash file automatically when the container starts
RUN echo "source /catkin_ws/devel/setup.bash" >> ~/.bashrc

RUN /bin/bash -c  "[ -L /usr/bin/python ] || sudo ln -s /usr/bin/python3 /usr/bin/python" 
# Command to run when starting the container, adjusted for your package and launch file
CMD ["/bin/bash", "-c", "source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash  && rosrun course_web_dev_ros tortoisebot_action_server.py"]