# Base image
FROM osrf/ros:noetic-desktop-full-focal

# Install required ROS packages
# Adding ROS packages required by your project for direct installation
RUN apt-get update && apt-get install -y \
    ros-noetic-genmsg \
    ros-noetic-geometry-msgs \
    ros-noetic-nav-msgs \
    ros-noetic-std-msgs \
    ros-noetic-actionlib-msgs \
    ros-noetic-actionlib \
    ros-noetic-rosbridge-server

# Set up the catkin workspace
RUN mkdir -p /catkin_ws/src
WORKDIR /catkin_ws

# Copy your ROS package source
COPY ./src /catkin_ws/src

# Build the workspace
RUN /bin/bash -c ". /opt/ros/noetic/setup.bash && catkin_make"

# Source the setup.bash file automatically when the container starts
RUN echo "source /catkin_ws/devel/setup.bash" >> ~/.bashrc

# Set SLOT_ROSBRIDGE_PORT environment variable
ENV SLOT_ROSBRIDGE_PORT=9091

# Command to run when starting the container, adjusted for your package and launch file
CMD ["/bin/bash", "-c", "source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && roslaunch course_web_dev_ros web.launch"]
