version: '3'
services:
  tortoisebot-ros2-gazebo:
    build:
      context: ./
      dockerfile: Dockerfile_gazebo
    image: tortoisebot-ros2-gazebo
    container_name: tortoisebot-ros2-gazebo_1
    network_mode: host
    environment:
      - "DISPLAY=${DISPLAY}"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    ports:
      - "11311:11311"  # Publish ROS master port

  tortoisebot-ros1-slam:
    build:
      context: ./
      dockerfile: Dockerfile_slam
    image: tortoisebot-ros2-slam
    container_name: tortoisebot-ros2-slam_1
    network_mode: host
    depends_on:
      - tortoisebot-ros2-gazebo
    environment:
      - "DISPLAY=${DISPLAY}"
      - "ROS_MASTER_URI=http://localhost:11311"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
